# Generated by Django 3.0.7 on 2020-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
