# Generated by Django 3.0.7 on 2020-06-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_page_is_home"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="page", unique_together={("url_part", "site")},
        ),
    ]
