# Generated by Django 3.0.7 on 2020-06-22 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSSLCertificate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapeSimpleGet',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
