# Generated by Django 3.0.7 on 2020-06-22 12:55

from django.db import migrations, models
import django.db.models.deletion
import scraper.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapeSimpleGet',
            new_name='ScrapeRequestsGet',
        ),
        migrations.CreateModel(
            name='ScrapeRequestsHeaders',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, scraper.models.ScraperPickleCache),
        ),
    ]
