# Generated by Django 3.0.7 on 2020-06-29 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_auto_20200628_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagebrowserscraper",
            name="wait_ms_before_screenshot",
            field=models.IntegerField(
                default=300,
                validators=[
                    django.core.validators.MaxValueValidator(4000),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
