# Generated by Django 3.0.7 on 2020-06-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('metric', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SSLMetric',
            new_name='SSLExpiration',
        ),
        migrations.CreateModel(
            name='PageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.SmallIntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
