# Generated by Django 3.0.7 on 2020-06-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('metric', '0003_auto_20200622_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContentLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('content_length', models.IntegerField(null=True)),
                ('sec_since_last_modified', models.IntegerField(null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
