# Generated by Django 3.0.7 on 2020-06-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metric", "0006_auto_20200622_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="headermetrics",
            name="elapsed_seconds",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
