# Generated by Django 3.0.7 on 2020-06-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_page_is_home"),
        ("metric", "0007_headermetrics_elapsed_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageRequestMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("status_code", models.SmallIntegerField()),
                ("content_length", models.IntegerField(null=True)),
                ("sec_since_last_modified", models.IntegerField(null=True)),
                ("elapsed_seconds", models.FloatField()),
                ("num_redirects", models.SmallIntegerField()),
                ("redirect_is_permanent", models.BooleanField(null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.Page"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveField(model_name="redirectmetrics", name="page",),
        migrations.DeleteModel(name="HeaderMetrics",),
        migrations.DeleteModel(name="RedirectMetrics",),
    ]
